<?php

$pages = [
    'home' => 'Home',
    'about' => 'About',
    'contact' => 'Contact',
    'service' => 'Service',
    'formation' => 'Formation',
    'formation_detail' => 'Formation Detail',
    'mesformations' => 'Mes-formation',
    'produit' => 'Produit',
    'register' => 'Register',
    'login' => 'Login',
    'logout' => 'Logout',
    'reali' => 'Reali',
    '404' => '404',
    'dashboard' => 'dashboard',
    'profile' => 'Profile',
    'client' => 'Client',
    'test' => 'test',
    'certificats' => 'Certificats',
    'admin' => 'admin',
    'telecharger_support' => 'telecharger_support',
    'telecharger_exercice' => 'telecharger_exercice',
    'soumettre_realisation' => 'soumettre_realisation',
    'paiement' => 'paiement',
];

// Table des pages autorisées (sécurisé)
$pages_allowed = [
    'admin' => 'pages/admin/index.php',
    'test' => 'pages/test.php',
    'home' => 'pages/overview.php',
    'about' => 'pages/about.php',
    'contact' => 'pages/contact.php',
    'formation' => 'pages/formation.php',
    'formation_detail' => 'pages/formation_detail.php',
    'service' => 'pages/service.php',
    'produit' => 'pages/produit.php',
    'register' => 'pages/register.php',
    'login' => 'pages/login.php',
    'reali' => 'pages/reali.php',
    'logout' => 'pages/logout.php',
    '404' => 'pages/404.php',
    'dashboard' => 'pages/dashboard.php',
    'profile' => 'pages/profile.php',
    'client' => 'pages/client.php',
    'certificats' => 'pages/certificats.php',
    'mesformations' => 'pages/mesformations.php',
    'telecharger_support' => 'pages/telecharger_support.php',
    'telecharger_exercice' => 'pages/telecharger_exercice.php',
    'soumettre_realisation' => 'pages/soumettre_realisation.php',
    'paiement' => 'pages/paiement.php'
];
